export const ENV_QUAKE_TABLE = 'QUAKE_TABLE';
export const ENV_QUAKE_TASK_CLUSTER = 'QUAKE_TASK_CLUSTER';
export const ENV_QUAKE_TASK_DEFINITION = 'QUAKE_TASK_DEFINITION';
export const ENV_QUAKE_TASK_SECURITY_GROUPS = 'QUAKE_TASK_SECURITY_GROUPS';
export const ENV_QUAKE_TASK_SUBNETS = 'QUAKE_TASK_SUBNETS';